@hostname=localhost
@port=7034
@host={{hostname}}:{{port}}

### get current weather request
GET https://{{host}}/weather/v1/current?latitude=38.5&longitude=-78.5
Content-Type: application/json

### get forecast weather request
GET https://{{host}}/weather/v1/forecast?latitude=38.5&longitude=-78.5
Content-Type: application/json

### get favorites weather request
GET https://{{host}}/weather/v1/favorites
Content-Type: application/json

### add favorites weather request
POST https://{{host}}/weather/v1/favorite
Content-Type: application/json

{
  "location": {
    "latitude": 38.5,
    "longitude": -78.5
  }
}

### add favorites weather request
DELETE https://{{host}}/weather/v1/favorite/1
Content-Type: application/json